version: "3"
services:
   master:
      container_name: jenkins-master
      image: docker:dind
      privileged: true
      volumes:
         - jenkins-docker-certs:/certs/client
         - jenkins-data:/var/jenkins_home
      ports:
         - 2376:2376
      environment:
         - DOCKER_TLS_CERTDIR=/certs
      networks:
         jenkins:
            aliases:
               - master

   worker:
      container_name: worker
      image: jenkinsci/blueocean
      ports:
         - "80:8080"
         - "50000:50000"
      environment:
         - DOCKER_HOST=tcp://master:2376
         - DOCKER_CERT_PATH=/certs/client
         - DOCKER_TLS_VERIFY=1
      volumes:
         - jenkins-docker-certs:/certs/client
         - jenkins-data:/var/jenkins_home
      networks:
         - jenkins

volumes:
   jenkins-data:
   jenkins-docker-certs:
networks:
   jenkins: 